### ISSUE TITLE
_recv_packet 函数 遇到错误返回，read_result并没有设置mysql. state=1 而是直接返回nil，导致下一次query失败

### ISSUE THREAD

**Issue by wedvefv** [openresty/lua-resty-mysql#104]
我们线上遇到一个问题，前一次的sql 执行出现了超时  failed to receive packet header:timeout， read_result函数就在841行返回_recv_packet收到的错误 ,但是没设置mysql.state  = 1 , 下一次继续send_query 出现 cannot send query in the current context: 2 的错误，不知道这算不算一个问题呢？

**Comment by wedvefv** [comment]
you mean i need read_result again when i get timeout error ?

**Comment by agentzh** [comment]
@wedvefv You cannot use a connection with fatal errors like timeout. You need to discard the current connection and call the `connect()` method to re-connect. Or you can adjust your timeout threshold.

**Comment by agentzh** [comment]
@wedvefv BTW, this place is considered English only. If you really want to use Chinese, please try our Chinese channels below:

https://forum.openresty.us/

https://groups.google.com/forum/#!forum/openresty

**Comment by wedvefv** [comment]
ok ok
