### ISSUE TITLE
world.sql.gz page was not found, resulting in a CI error

### ISSUE THREAD

**Issue by xiaocang** [openresty/lua-resty-mysql#126]
As mentioned below, the `world.sql.gz` used in CI are no longer available, so what resources should be used instead?

https://github.com/openresty/lua-resty-mysql/blob/77805ebff1738513cb350d7927f2133561d7efe9/.travis/initializedb.sh#L84

``` bash
wget https://downloads.mysql.com/docs/world.sql.gz
--2021-07-08 21:58:46--  https://downloads.mysql.com/docs/world.sql.gz
Resolving downloads.mysql.com (downloads.mysql.com)... 137.254.60.14
Connecting to downloads.mysql.com (downloads.mysql.com)|137.254.60.14|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-07-08 21:58:50 ERROR 404: Not Found.
```

**Comment by xiaocang** [comment]
cc @rainingmaster

**Comment by rainingmaster** [comment]
I see, it seems that `world.sql.gz` has been deleted, should we put it into this repo?

**Comment by rainingmaster** [comment]
I have found a download link here: https://github.com/kakakakakku/mysql-world-database-dockerfiles/blob/master/5.5/world.sql.gz

**Comment by xiaocang** [comment]
> I have found a download link here: https://github.com/kakakakakku/mysql-world-database-dockerfiles/blob/master/5.5/world.sql.gz

emm... this link does not look like the official mysql maintained

**Comment by rainingmaster** [comment]
> > I have found a download link here: https://github.com/kakakakakku/mysql-world-database-dockerfiles/blob/master/5.5/world.sql.gz
> 
> emm... this link does not look like the official mysql maintained

I think the official mysql don't want to maintain this file...
