### ISSUE TITLE
install by luarocks error

### ISSUE THREAD

**Issue by NeoyeElf** [openresty/lua-resty-mysql#137]
When I run `RUN luarocks make`, the error occurs: 

```
Installing https://luarocks.org/lua-resty-mysql-0.15-0.rockspec

91mfatal: remote error:

The unauthenticated git protocol on port 9418 is no longer supported.

Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```

according to the [2021-09-01-improving-git-protocol-security-github](https://github.blog/2021-09-01-improving-git-protocol-security-github/), the `source.url` in https://luarocks.org/lua-resty-mysql-0.15-0.rockspec is "git://github.com/openresty/lua-resty-mysql", which is no longer supported by github

**Comment by dndx** [comment]
Hello @NeoyeElf,

This library is not officially distributed via LuaRocks and `0.15` is an really outdated version. Try using the latest release tag instead: https://github.com/openresty/lua-resty-mysql/tags

**Comment by NeoyeElf** [comment]
solved by add `git config --global url."https://".insteadOf git://`
