### ISSUE TITLE
连Mysql数据库，结果乱码，数据库编码为utf-8

### ISSUE THREAD

**Issue by lenxeon** [openresty/lua-resty-mysql#20]
如何修改编码呢

local mysql = require "resty.mysql"
local db,err = mysql:new()
if not db then
        ngx.say("failed to instantiate mysql: ",err)
        return
end

db:set_timeout(1000)

local ok,err,errno,sqlstate = db:connect{
        host = "127.0.0.1",
        port = 3306,
        database = "db_blog",
        user = "root",
        password = "admin",
        max_package_size = 1024,
        charset = "utf-8"
}
if not ok then
        ngx.say("failed to connect: ", err, ": ", errno, " ", sqlstate)
        return
end

res,err,errno,sqlstate = db:query("select * from wp_terms")
if not res then
        ngx.say("bad result: ", err, ": ", errno, ": ", sqlstate, ".")
        return
end

local cjson = require "cjson"
ngx.say(cjson.encode(res))

结果
[{"term_group":"0","name":"????","term_id":"1","slug":"help"},{"term_group":"0","name":"??","term_id":"2","slug":"novel"},{"term_group":"0","name":"??","term_id":"3","slug":"service"},{"term_group":"0","name":"main_menu","term_id":"4","slug":"main_menu"},{"term_group":"0","name":"??","term_id":"5","slug":"about"},{"term_group":"0","name":"????","term_id":"6","slug":"info"},{"term_group":"0","name":"????","term_id":"7","slug":"notice"},{"term_group":"0","name":"????","term_id":"8","slug":"job"},{"term_group":"0","name":"????","term_id":"9","slug":"cooperate"},{"term_group":"0","name":"????","term_id":"10","slug":"%e5%bc%82%e5%b8%b8%e5%a4%84%e7%90%86"}]

**Comment by pen886** [comment]
support charset：

[code]:
db:query("SET NAMES utf8")
res,err,errno,sqlstate = db:query("select * from wp_terms")
if not res then
ngx.say("bad result: ", err, ": ", errno, ": ", sqlstate, ".")
return
end

**Comment by agentzh** [comment]
@pen886 MySQL's charset setting is a mess. Even if you have UTF-8 encoded table, the default character encoding used on the MySQL connections can still something else. The simplest and most efficient way is to add the following lines under the `[mysqld]` section in your MySQL server's `my.cnf` file and reload the database:

```ini
character-set-server=utf8
collation-server=utf8_general_ci
```
