### ISSUE TITLE
get_reused_times always return zero

### ISSUE THREAD

**Issue by njentit** [openresty/lua-resty-mysql#23]
I add below code after connect, but it always return zero on every request.
local times, err = db:get_reused_times()
                if not times then
                    ngx.say("failed to get get_reused_times: ", err)
                    return
                end
                ngx.say("connection reused ", times," times.")

**Comment by agentzh** [comment]
@njentit Have you ever put your connections into the connection pool via the `set_keepalive` method? If not, then your connection pool is always empty and you won't have any reused connections. In addition, you need to ensure your `set_keepalive` method is not ever failing by always checking its return values in your Lua code.

**Comment by njentit** [comment]
I'm running 1 worker_processes openresty ver. 1.7.10.1 on osx Lion with mysql 5.6. Here my nginx config, it just your sample config with addition printing get_reused_times after db:connect

location /test {
            content_by_lua '
                local mysql = require "resty.mysql"
                local db, err = mysql:new()
                if not db then
                    ngx.say("failed to instantiate mysql: ", err)
                    return
                end

                db:set_timeout(1000) -- 1 sec

                local ok, err, errno, sqlstate = db:connect{
                    host = "127.0.0.1",
                    port = 3306,
                    database = "testdb",
                    user = "test",
                    password = "test123",
                    max_packet_size = 1024 * 1024 }

                if not ok then
                    ngx.say("failed to connect: ", err, ": ", errno, " ", sqlstate)
                    return
                end

                ngx.say("connected to mysql.")

                local times, err = db:get_reused_times()
                if not times then
                    ngx.say("failed to get get_reused_times: ", err)
                    return
                end
                ngx.say("connection reused ", times," times.") 

                local res, err, errno, sqlstate =
                    db:query("drop table if exists cats")
                if not res then
                    ngx.say("bad result: ", err, ": ", errno, ": ", sqlstate, ".")
                    return
                end

                res, err, errno, sqlstate =
                    db:query("create table cats "
                             .. "(id serial primary key, "
                             .. "name varchar(5))")
                if not res then
                    ngx.say("bad result: ", err, ": ", errno, ": ", sqlstate, ".")
                    return
                end

                ngx.say("table cats created.")

                res, err, errno, sqlstate =
                    db:query("insert into cats (name) "
                             .. "values (\'Bob\'),(\'\'),(null)")
                if not res then
                    ngx.say("bad result: ", err, ": ", errno, ": ", sqlstate, ".")
                    return
                end

                ngx.say(res.affected_rows, " rows inserted into table cats ",
                        "(last insert id: ", res.insert_id, ")")

                -- run a select query, expected about 10 rows in
                -- the result set:
                res, err, errno, sqlstate =
                    db:query("select * from cats order by id asc", 10)
                if not res then
                    ngx.say("bad result: ", err, ": ", errno, ": ", sqlstate, ".")
                    return
                end

                local cjson = require "cjson"
                ngx.say("result: ", cjson.encode(res))

                -- put it into the connection pool of size 100,
                -- with 10 seconds max idle timeout
                local ok, err = db:set_keepalive(10000, 100)
                if not ok then
                    ngx.say("failed to set keepalive: ", err)
                    return
                end

                ngx.say("set_keepalive success")
            ';
        }
  }

set_keepalive return success, next code executed print zero result. Thanks.

**Comment by agentzh** [comment]
@njentit I've tried your example on my side and it works perfectly as expected:

```
agentzh@w530 ~ $ curl localhost:8080/test
connected to mysql.
connection reused 0 times.
table cats created.
3 rows inserted into table cats (last insert id: 1)
result: [{"name":"Bob","id":"1"},{"name":"","id":"2"},{"name":null,"id":"3"}]
set_keepalive success
agentzh@w530 ~ $ curl localhost:8080/test
connected to mysql.
connection reused 1 times.
table cats created.
3 rows inserted into table cats (last insert id: 1)
result: [{"name":"Bob","id":"1"},{"name":"","id":"2"},{"name":null,"id":"3"}]
set_keepalive success
agentzh@w530 ~ $ curl localhost:8080/test
connected to mysql.
connection reused 2 times.
table cats created.
3 rows inserted into table cats (last insert id: 1)
result: [{"name":"Bob","id":"1"},{"name":"","id":"2"},{"name":null,"id":"3"}]
set_keepalive success
```

You can see that the reused times are increasing monotonically.

Maybe you have turned off the Lua code cache by configuring `lua_code_cache off`? The cosocket connection pools require the Lua code cache to work properly.

**Comment by njentit** [comment]
it working greats, sorry i missed that. Sorry for using issue as this actually not an issue, i'll use group for next question if any. I'm currently porting one of php project into lua+openresty.
Thanks for great work.
