### ISSUE TITLE
specific charset encoding is needed to implement

### ISSUE THREAD

**Issue by amewayne** [openresty/lua-resty-mysql#27]
there is a case that when i use this lib to connect mysql, a warning which says [unkown charset num:0, charset will be set as utf8] will occur on database server. so i think that connect function needs a parameter for charset encoding. i saw agenth's comment which said that u don't like to set names on client and there is default charset on server though.....just an advice~

**Comment by agentzh** [comment]
@hqweiyu Will you provide a patch please?
