### ISSUE TITLE
能给一个把mysql封装成一个模块的例子吗

### ISSUE THREAD

**Issue by jessicaHY** [openresty/lua-resty-mysql#35]
能给一个把mysql封装成一个模块的例子吗，传一个sql语句，返回结果的。自己测试了很久达不到那个吞吐量，又不知道问题出在哪里

**Comment by agentzh** [comment]
@jessicaHY Please, do not use Chinese here. This place is considered English only. If you really want to use Chinese, please join and post to the openresty (Chinese) mailing list. Please see https://openresty.org/#Community for more details.

Also, general questions like this should go to the mailing lists. This Issues board should be left for real "issues".

Thanks for your cooperation.

**Comment by jessicaHY** [comment]
OK
