### ISSUE TITLE
a bug ???

### ISSUE THREAD

**Issue by heyuanlong** [openresty/lua-resty-mysql#36]
765  local function read_result(self, est_nrows)
766     if self.state ~= STATE_COMMAND_SENT then
767        return nil, "cannot read result in the current context: " .. self.state
768   end

bug???
resty/mysql.lua:794: attempt to concatenate field 'state' (a nil value)

**Comment by agentzh** [comment]
@heyuanlong Will you provide a minimal and self-contained code example that can reproduce this?

**Comment by heyuanlong** [comment]
我的代码
`
if mysqlConn then
        local res, err, errno, sqlstate = mysqlConn:read_result()
        while err == "again" do
            res, err, errno, sqlstate = mysqlConn:read_result()
        end
        local ok, err           = mysqlConn:set_keepalive(10000, 100)
        if not ok then
            mysqlConn:close()
            ok = false
            db_type = db_type + mysql_type
            err = "MySQL.Error ( "..(err or "null").." ) "
        end
    end 
`
报的错误：
2016/04/29 16:57:30 [error] 17843#0: *46412 lua entry thread aborted: runtime error: /data/sns.kobox.tv/lib/sns_common/resty/mysql.lua:794: attempt to concatenate field 'state' (a nil value)
stack traceback:
coroutine 0:
	/data/sns.kobox.tv/lib/sns_common/resty/mysql.lua: in function 'read_result'
	/data/matchvs.com/lib/user/connection.lua:72: in function 'releaseConn'

**Comment by heyuanlong** [comment]
if mysqlConn then
        local res, err, errno, sqlstate = mysqlConn:read_result()
        while err == "again" do
            res, err, errno, sqlstate = mysqlConn:read_result()
        end
        local ok, err           = mysqlConn:set_keepalive(10000, 100)
        if not ok then
            mysqlConn:close()
            ok = false
            db_type = db_type + mysql_type
            err = "MySQL.Error ( "..(err or "null").." ) "
        end
    end

**Comment by heyuanlong** [comment]
```
local function read_result(self)
              if self.state ~= STATE_COMMAND_SENT then
        return nil, "cannot read result in the current context: " .. (self.state or "nil")--增加判断吧
    end
```

**Comment by agentzh** [comment]
@heyuanlong Please do not use Chinese here. Thank you.

Regarding the issue, yes, we should add the `or ""` part there. Patches welcome :)

**Comment by agentzh** [comment]
Committed a fix to git master. Thanks for the report.
