### ISSUE TITLE
/etc/test.crt ?

### ISSUE THREAD

**Issue by chipitsine** [openresty/lua-resty-mysql#38]
where can I get that cert/key ?

https://github.com/openresty/lua-resty-mysql/blob/master/t/ssl.t#L96

should I generate it on the fly ?

**Comment by agentzh** [comment]
@chipitsine Oh, this is sloppy. Thanks for the catch. I'll check it out.

**Comment by agentzh** [comment]
@chipitsine Thanks for the report! I've just checked in the `test.crt` and `test.key` files to the git repository, under `t/data/`. The `my.cnf` file should contain the following lines under `[mysqld]`:

```
ssl-ca=/etc/my.cnf.d/test.crt
ssl-cert=/etc/my.cnf.d/test.crt
ssl-key=/etc/my.cnf.d/test.key
```

assuming you have copied the `test.crt` and `test.key` files from the git repo to `/etc/my.cnf.d/`.
