### ISSUE TITLE
Connection was broken

### ISSUE THREAD

**Issue by sdmrnv** [openresty/lua-resty-mysql#39]
Hello!

I have 2 identical virtual servers. When I have connected in lua script to local MySQL at first of these servers - all OK. But when I try to do this at second server my browser broke connection to local MySQL. If I try to connect from second server (via lua) to first MySQL I get this error:

"failed to connect: Host '<ip>' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts': 1129 nil" 

I don't understand what difference inter my servers.....I have already copy my.cnf, test.lua script, etc from first server to second but it has no effect. One server works, another - not work.....Mystic....

I'd appreciate any help!

**Comment by agentzh** [comment]
@sdmrnv Where did you get that error message in the first place? In nginx's error log file or in your mysqld server's error log file?

Please try the latest OpenResty 1.9.15.1 RC2 version which contains a fix for interrupted MySQL connections:

http://openresty.org/download/openresty-1.9.15.1rc2.tar.gz

But you really want to enable the MySQL connection pool to avoid too many short connections to your MySQL server in the first place. See

https://github.com/openresty/lua-resty-mysql#set_keepalive

**Comment by sdmrnv** [comment]
@agentzh I have seen nginx log and found that the problem was in sha1 library. After **apt-get install libssl-dev** and reconfiguring nginx I have: + sha1: using system crypto library. Now all works!!!

Thank you very much for idea to see mysql log!

**Comment by agentzh** [comment]
@sdmrnv Glad you figured it out yourself.
