### ISSUE TITLE
lua-resty-mysql包装函数过程出现的诡异问题,我错在哪儿呢,求正确包装方式

### ISSUE THREAD

**Issue by pronan** [openresty/lua-resty-mysql#40]
春哥,我用直接用中文了.大环境:win10 64 + openresty-1.9.7.4-win32.
我自己做了一个基于lua-resty-mysql查询的包装函数query, 主要是为了方便,不用去管连接的建立和释放.比如在content_by_lua_block中这样用:

    local query=require"mylib.query"
    local res1=query('SELET * FROM table1')
    local res2=query('SELET name,age FROM table1 WHERE id=1')

这个函数在以下情况都表现正确:
1.只提交了一个sql 查询语句,无论合法还是出错的.
2.提交了多个合法的sql查询语句,
但是,如果提交多个查询,且其中一个查询出错(比如statement的语法有错),那么随后的最后一个合法查询就会异常.比如说我先后提交了两个查询:

    query('UPDATE WHERE (id = 1)') --语法错误
    query('SELET * FROM table1') --正常  
    query('SELET * FROM table1') --这个合法语句将异常,返回nil,nil,nil,nil

这是我定义的query函数:

    local mysql = require "resty.mysql"

    local connect_table = {
        host = '127.0.0.1', port = 3306,
        user = 'root', password = '',
        database = 'test',
    }

    local function query(sql_statements)
        local db = ngx.ctx._db
        local res, err, errno, sqlstate;
        -- 如果第一次建立连接或上一个链接出错, 则新建
        if not db or db._query_err~=nil then
            db, err = mysql:new()
            if not db then
                return db, err
            end
            db:set_timeout(10000) 
            res, err, errno, sqlstate = db:connect(connect_table)
            if not res then
                return res, err
            end
            -- 将db绑定到ctx中, 方便共用
            ngx.ctx._db = db
        else
            --这里表示连接复用(上一次连接是正常的)
        end
        -- 开始使用连接进行查询
        res, err, errno, sqlstate =  db:query(sql_statements)
        -- 将err值绑定到db上, 以供下次提交查询语句时判断是否需要新建连接
        db._query_err = err
        return res, err, errno, sqlstate
    end
    return query

**Comment by agentzh** [comment]
Please, do not use Chinese here. This place is considered English only. If you
really want to use Chinese, please join and post to the openresty (Chinese)
mailing list instead. Please see https://openresty.org/en/community.html Thanks for
your cooperation.
