### ISSUE TITLE
why longlong column not number?

### ISSUE THREAD

**Issue by Yongke** [openresty/lua-resty-mysql#45]
hi, @agentzh 

It's just a small & quick question. 
Why you commented line below? ;-) Protocol::MYSQL_TYPE_LONGLONG should also be number?

```
-- converters[0x08] = tonumber  -- long long
```

**Comment by agentzh** [comment]
@Yongke Because `long long` is 64-bit and a Lua number cannot hold a full-size 64-bit integer, we have to turn it to a Lua string instead.

**Comment by Yongke** [comment]
OK. Got it, forgot that number is actually float. Thank very much. Just closing it.
