### ISSUE TITLE
how to avoid too many connections error ?

### ISSUE THREAD

**Issue by pronan** [openresty/lua-resty-mysql#56]
ubuntu server 14.04 (512M, Aliyun ECS),lua-resty-mysql (0.17) and openresty (1.11.2.2). When I attempt to insert about 100K tiems, the database failed about 7k items, some are due to `too many connections`,  the other are out of memory.  

I set the pool size to 50 in lua layer. and use the default settting in mysql server layer. I also wrap the query logic to a module and use it via require:
```
local driver = require "mysql"

local CONNECT_TABLE = { 
        host     = "127.0.0.1", 
        port     = 3306, 
        database = "test", 
        user     = 'root', 
        password = '', }
local CONNECT_TIMEOUT = 1000
local IDLE_TIMEOUT = 10000
local POOL_SIZE = 50

local function query(statement, rows)
    -- utils.loger(statement)
    local db, err = driver:new()
    if not db then
        return nil, err
    end
    db:set_timeout(CONNECT_TIMEOUT) 
    local res, err, errno, sqlstate = db:connect(CONNECT_TABLE)
    if not res then
        return nil, err, errno, sqlstate
    end
    res, err, errno, sqlstate =  db:query(statement, rows)
    if res ~= nil then
        local ok, err = db:set_keepalive(IDLE_TIMEOUT, POOL_SIZE)
        if not ok then
            return nil, err
        end
    end
    return res, err, errno, sqlstate
end

return query
```

**Comment by pronan** [comment]
also I'm not sure about whether `to many connections` is normal in this situation.

**Comment by agentzh** [comment]
@pronan It is your responsibility to limit backend concurrency level by means of libraries like `lua-resty-limit-traffic`.

**Comment by pronan** [comment]
Sorry, I've checked the document but I don't quite get it and don't know how to use it in my `create.lua`. Let me provide more info. 
The whole process is  simple: I insert the huge itmes via making a *single* request `/create` in browser and then trigger a lua loop in nginx.  During the loop, I think there should be only one connection to mysql server. So I don't know why the error `too many connections` occurred. 

Am I wrong? Or is it related to the Non-blocking design of openresty?

## nginx.conf
```

        location = /create {
            content_by_lua_file create.lua;
        }

```
## create.lua
```
local query = require "query"
for i, e in ipairs(huge_array) do
    local res, err = query(string.format('insert into sbk (c1, c2) values (%s, %s);', e[1],e[2]))
end
```

If not ok, I could provide the server environment.
