### ISSUE TITLE
please delete

### ISSUE THREAD

**Issue by destanyinside** [openresty/lua-resty-mysql#66]
del

**Comment by agentzh** [comment]
@destanyinside Please prepare a *minimal* and *standalone* example that we can easily run and reproduce the issue on our side. By *minimal*, it means that you should keep removing things while still keeping the issue reproducible. By *standalone*, you should add all the necessary bits and also steps to reproduce, including database initialization SQL statements.

**Comment by agentzh** [comment]
@destanyinside Also, please fix your markdown formatting.

**Comment by agentzh** [comment]
@destanyinside Also, make sure you give the *actual output* from your minimal example. Please don't make us guess.
