### ISSUE TITLE
set_keepalive() fails after concatenated SQL-query sent

### ISSUE THREAD

**Issue by sburn** [openresty/lua-resty-mysql#72]
I'm getting "cannot be reused in the current connection state: 2" error when trying to set_keepalive() mysql connection after concatenated SQL-query (multiple sql queries in one request) sent.

**Comment by sburn** [comment]
Here is the code (your slightly modified sanity test-15):

location /t {
content_by_lua '
            local ljson = require "ljson"

            local mysql = require "resty.mysql"
            local db = mysql:new()

            db:set_timeout(1000) -- 1 sec

            local ok, err, errno, sqlstate = db:connect({
                path = "$TEST_NGINX_MYSQL_PATH",
                database = "ngx_test",
                user = "ngx_test",
                password = "ngx_test"})

            if not ok then
                ngx.say("failed to connect: ", err, ": ", errno, " ", sqlstate)
                return
            end

            ngx.say("connected to mysql: ", db:get_reused_times())

            local ok, err = db:set_keepalive()
            if not ok then
                ngx.say("failed to set keepalive: ", err)
                return
            end

            ok, err, errno, sqlstate = db:connect({
                path = "$TEST_NGINX_MYSQL_PATH",
                database = "ngx_test",
                user = "ngx_test",
                password = "ngx_test"})

            ngx.say("connected to mysql: ", db:get_reused_times())

            local bytes, err =
                db:send_query("select * from cats order by id asc; select NOW(); ")
            if not bytes then
                ngx.say("bad result: ", err, ".")
                return
            end

            ngx.say("bytes sent ok: ", bytes)

            local ok, err = db:set_keepalive()
            if not ok then
                ngx.say("failed to set keepalive: ", err)
                return
            end
    ';
    }

**Comment by agentzh** [comment]
@sburn You failed to read the mysql response data from the wire. A connection with unread data cannot be safely reused, obviously, otherwise the next request reusing the data would get those unread responses. Please read the documentation for more details. This is an FAQ. Better google or search the error message keywords before filing a new issue to save your time (and also ours). Thank you for your cooperation.

**Comment by sburn** [comment]
Thanks for you reply. As for me, this is not entirely clear even after reading the documentation. The obvious for the developer is not obvious to the user, I guess. I can't find in the docs where is written about set_keepalive() and send_query() incompatibility in case of sending requests that do not require any response reading.

**Comment by agentzh** [comment]
@sburn Every MySQL query does yield at least one response. Sometimes even multiple.

**Comment by falves1** [comment]
I have the same issue, but in this case I do read the result set and send it back to the client, yet, keepalive fails:
