### ISSUE TITLE
Do you not need begin,commit transaction to insert data concurrently?

### ISSUE THREAD

**Issue by huifeidexingyuner** [openresty/lua-resty-mysql#80]
This place is for bug reports and development discussions only. For general questions and
discussions, please join the openresty-en mailing list instead: https://openresty.org/en/community.html

Ensure you have provided the following details while reporting a problem:

* The exact version of the related software, including but not limited to the OpenResty version
(if any), the NGINX core version, ngx_lua module version, this Lua library''s version,
and operating system version.

* A minimal and standalone test case that others can easily run on their side and
reproduce the issue you are seeing.

* Do not simply say "something is broken" or "something does not work". Always provide
as much details as possible. Always describe the symptoms and your expected results.

Please, do not use Chinese here. This place is considered English only. If you
really want to use Chinese, please join and post to the openresty (Chinese)
mailing list instead. Please see https://openresty.org/en/community.html Thanks for
your cooperation.

**Comment by yukixia** [comment]
hello, I would like to ask whether the transaction has been solved by using lua_resty_mysql

**Comment by agentzh** [comment]
Depending on your own business requirements. Usually you don't. It's more about a mysql server usage question.
