### ISSUE TITLE
db:query() can't execute sql which contain "delimiter // ... //"

### ISSUE THREAD

**Issue by Bevisy** [openresty/lua-resty-mysql#85]
i want to add a procedure into mysql like this:  
```sh
DROP PROCEDURE
IF EXISTS delete_expired_cluster_events;
delimiter //

CREATE PROCEDURE xxx (
       ...
)
BEGIN
        ...
END;
//
delimiter ;
```
then i got a syntax error like this `"You have an error in your SQL syntax; check the anual that corresponds to your MySQL server version for the right syntax to user near 'delimiter // ...' at line 1"`.  
But the sql syntax was run well with mysql console.So I want to know where I am doing something wrong.

**Comment by agentzh** [comment]
@Bevisy The `delimiter` command is defined by the standard `mysql` client program, not by the wire protocol or the server implementation. This library does not implement any mysql CLI commands, at least not yet.

**Comment by Bevisy** [comment]
@agentzh Thank you for your reply. If i want to add FUNCTION by lua-resty-mysql, how should i do? i have no idea about this.  
The function of the FUNCTION is to periodically delete the expired rows in the table.

**Comment by agentzh** [comment]
@Bevisy The simplest way is to escape any special chars in your procedure declaration strings by some Lua code instead of implementing that `delimiter //` feature.

**Comment by Bevisy** [comment]
@agentzh Thanks a lot. i will have a try.
