### ISSUE TITLE
connot connect Azure Database for MySQL

### ISSUE THREAD

**Issue by fc13240** [openresty/lua-resty-mysql#92]
connot connect Azure Database for MySQL, the error is:
old pre-4.1 authentication protocol not supported

**Comment by FrancisHe** [comment]
I got the same problem, does anybody solved this problem?

**Comment by fc13240** [comment]
我更新版本库可以解决，如果是centos系统，请以下文章参考更新：[https://www.tech-field.org/articles/2021/01/04/1609752680599.html](https://www.tech-field.org/articles/2021/01/04/1609752680599.html)
